version: "3"
services: 
  api-server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file: ./config/config.env
    ports:
    - "3000:3000"
    networks:
    - storybooks-app
    depends_on:
    - mongo

  mongo:
    image: mongo:3.6-xenial
    environment: 
    - MONGO_INIT_DATABASE=storybooks
    ports:
    - "27017:27017"
    networks:
    - storybooks-app
    volumes:
      - mongo-data:/data/db


networks:
  storybooks-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local